---
title: "Visualization Customization"
author: "Jingjing"
date: '2022-07-25'
output: html_document
---

**Everything put within the geom...()**


Size:

* Constant (numeric)
  + `size = constant` 
* Variable (numeric or ordinal categorical)
  + `aes(size = variable)`
  
  
Alpha

* Constant (number between 0 (transparent) and 1 (opaque))
  + `alpha = constant`
* Variable (numeric or ordinal categorical)
  + `aes(alpha = variable)`
  + has transparency gradient
  
  
Shape

* Constant (number between 0 and 25)
  + `shape = constant` (default is 16)
* Variable (categorical if less than 26 options)
  + `aes(shape = variable)`
  
  
Color

* Constant
  + `See colors()`
  + `color = constant` (hex code)
* Variable (Numeric (gradient) or Categorical/Factor (distinct))
  + `aes(color = variable)`
* Color for boxplots, violin plots, barplots
* Outline color Constant
  + `See colors()`
  + `color = constant`
* Outline color Variable
  + `aes(color = variable)`


Fill

* Constant
  + `See colors()`
  + `fill = constant`
* Variable (Categorical/Factor)
  + `aes(fill = variable)`
  
  
Line Type (dotted, straight etc.)

* Constant (0-6 or name of line type) --> diff kinds of lines
* `lty = constant`
* Variable(categorical/factor)
* `aes(lty = variable)`


Line Width

* Constant (numeric)
  + `lwd = constant` (1, 2, 3...)
* Variable (don't recommend, numeric)
  + `aes(lwd = variable)`
  
  
Facets

* change colors of multiple curves on density graph
  + set `color = categorical_variable`
* Facets: `facet_wrap(~categorical_variable)` (splits into multiple graphs)


Annotations

* `annotate("text", x = x, y = y, label = "Bitcoin...")` 
* gives annotations, little text boxes and some (x, y) point
* `geom_abline()` adds a line at some y on graph
  
  